spring.application.name=demo

spring.security.user.name=vivin
spring.security.user.password=123

spring.datasource.url=jdbc:postgresql://localhost:5432/teluskoSpringSecurity
spring.datasource.username = postgres
spring.datasource.password = root
